#pragma once

enum Event
{
    SHUTDOWN = 1,
    NONE,
    TIMER_TIMEOUT,
    PAYMENT_FAILED,
    PAYMENT_SUCCESS,
    USER_CHOICE_BTN1_PRESSED,
    USER_CHOICE_BTN2_PRESSED,
    USER_CHOICE_BTN3_PRESSED,
    USER_CHOICE_BTN4_PRESSED
};